console.log("***************************Step1*********************************");
var sweety="Sweety";
var cutie="Cutie";
console.log("Before Swaping Names:");
console.log("sweety:", sweety);
console.log("cutie:", cutie);
var temp=sweety;
sweety=cutie;
cutie=temp;
console.log("After Swaping Names:");
console.log("sweety:", sweety);
console.log("cutie:", cutie);
console.log("***************************Step2*********************************");
var num1=100;
var num2=200;
var num3=300;
console.log("Before Swaping Numbers:");
console.log("Num1:", num1);
console.log("Num2:", num2);
console.log("Num3:", num3);
var temp=num1;
num1=num2;
num2=num3;
num3=num1;
num3=temp;
console.log("After Swaping Numbers:");
console.log("Num1:", num1);
console.log("Num2:", num2);
console.log("Num3:", num3);