var myFullName;
console.log(myFullName);
console.log("****************************************************************************************");
myFullName="Kanchan Choudhari";
console.log("My Name is:",myFullName);
console.log("*****************************************************************************************");
myFullName="Kanchan Ashish Choudhari";
console.log("My Full Name is:",myFullName);
console.log("******************************************************************************************");
var myLove="I Love only JS";
console.log(myLove);
console.log("*******************************************************************************************");
var firstName="Kanchan";
var lastName="Choudhari";
var age="26";
var address="Kalewadi, Pune"
var pinCode="411017";
var gender="Female";
var isMarried="Yes";
console.log("First Name",firstName);
console.log("Last Name:",lastName);
console.log("Age:",age);
console.log("Address:",address);
console.log("Pincode:",pinCode);
console.log("Gender:",gender);
console.log("Married:",isMarried);
console.log("*******************************************************************************");
