console.log("***************************Step1*********************************");
var age=26;
var city='Pune';
var isMarried=true;
console.log("Age:",age,",","Type:" ,typeof age);
console.log("City:",city,",","Type:" ,typeof city);
console.log("Marital Status:",isMarried,",","Type:" ,typeof isMarried);
console.log("***************************Step2*********************************");
console.log("Difference between null and undefined:");
console.log("Undefined value means variable is declared but does not initialize any value which is called as undefind value and null value is empty value or no value. It means nothing.");